### ISSUE TITLE
import reverb error,raise TypeError, 'Regexp cannot be negated'

### ISSUE THREAD

**Issue by ZhuShaoQiang** [deepmind/reverb#123]
I am using "Macos 13.1", python 3.10.9. conda env.
I install reverb using:
`pip install reverb`
res is:
```
Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
Collecting reverb
  Downloading https://mirrors.cloud.tencent.com/pypi/packages/10/69/1800d4345e0562260fa0818f6ac50d2f43d4595f33743c9e2c655709d86d/reverb-2.0.1.zip (3.4 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: reverb
  Building wheel for reverb (setup.py) ... done
  Created wheel for reverb: filename=reverb-2.0.1-py3-none-any.whl size=3672 sha256=4251691fdcd05b24bd6d3e75250155419fab8e5f0e5749c9a148cfe984c2f26e
  Stored in directory: /Users/****/Library/Caches/pip/wheels/93/05/62/087259bf1945fa284ee12fa3e58ae6f930a272999f4ea9f56e
Successfully built reverb
Installing collected packages: reverb
Successfully installed reverb-2.0.1
```

and enter python:
```bash
python
```
in this interactive mode, I import this:
```python
import reverb
```
and res is :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/*********/miniforge3/envs/constrastive_rl/lib/python3.10/site-packages/reverb.py", line 64
    raise TypeError, 'Regexp cannot be negated'
                   ^
SyntaxError: invalid syntax
```
I don't know what happend, and cannot find the solution in Internet.

**Comment by ZhuShaoQiang** [comment]
if I install dm-reverb like this:

```bash
pip install dm-reverb
```
the res is like this:
```Looking in indexes: https://mirrors.cloud.tencent.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement dm-reverb (from versions: none)
ERROR: No matching distribution found for dm-reverb
```

**Comment by ZhuShaoQiang** [comment]
sorry, I didn't notice that this is an old lib, I will try something else.
