### ISSUE TITLE
Cannot import reverb

### ISSUE THREAD

**Issue by marvosyntactical** [deepmind/reverb#20]
After installing reverb for tf-agents using
```
pip3 install tf-agents[reverb]
```

I cannot import reverb because of this FileNotFoundError:

```Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import reverb
2020-11-01 13:34:47.428913: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/silver/.mujoco/mujoco200/bin
2020-11-01 13:34:47.428939: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/silver/.local/lib/python3.6/site-packages/reverb/__init__.py", line 33, in <module>
    from reverb.dataset import ReplayDataset
  File "/home/silver/.local/lib/python3.6/site-packages/reverb/dataset.py", line 25, in <module>
    from reverb.cc.ops import gen_dataset_op
  File "/home/silver/.local/lib/python3.6/site-packages/reverb/cc/ops/gen_dataset_op.py", line 4, in <module>
    "libgen_dataset_op_gen_op.so"))
  File "/home/silver/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/silver/.local/lib/python3.6/site-packages/reverb/cc/ops/libgen_dataset_op_gen_op.so: undefined symbol: _ZN10tensorflow4data15DatasetOpKernel11TraceStringEPNS_15OpKernelContextEb
```

When I subsequently try to exit the python shell using Ctrl^D it prints this before exiting:
```
Exception ignored in: <bound method Buckets.__del__ of <tensorflow.python.eager.monitoring.ExponentialBuckets object at 0x7f6234677438>>
Traceback (most recent call last):
  File "/home/silver/.local/lib/python3.6/site-packages/tensorflow/python/eager/monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'
```

```
$ pip3 freeze | grep reverb
dm-reverb==0.1.0
dm-reverb-nightly==0.2.0.dev20201101
reverb==2.0.1
```
It appears I also have some other package named reverb installed (https://pypi.org/project/reverb/), could this be the problem? It also cannot be uninstalled:
```
Found existing installation: reverb 2.0.1
Uninstalling reverb-2.0.1:
  Would remove:
    /home/silver/.local/lib/python3.6/site-packages/*
  Would not remove (might be manually added):
```
After printing this it doesnt do anything anymore.

**Comment by wookayin** [comment]
DM Reverb requires TensorFlow version >= 2.4. However TF 2.4 is not released yet, so you should use `tf-nightly` (TF 2.4 release candidates are coming soon).

**Comment by marvosyntactical** [comment]
Im running tf-nightly==2.5.0.dev20201029

**Comment by marvosyntactical** [comment]
This command fixed my issue:
```
pip3 install --force-reinstall  --use-feature=2020-resolver tf-nightly && pip3 install --force-reinstall --use-feature=2020-resolver tfp-nightly && pip3 install --force-reinstall --use-feature=2020-resolver dm-reverb-nightly
```
