### ISSUE TITLE
acme tutorial failing due to "Table priority_table at localhost:X does not have a signature."

### ISSUE THREAD

**Issue by rdevon** [deepmind/reverb#98]
I'm attempting to run through the acme tutorial and I'm running into an error that I believe is related to reverb:
https://github.com/deepmind/acme/issues/215

The full trace:
```
ValueError                                Traceback (most recent call last)
Input In [53], in <cell line: 6>()
----> 6 dataset = datasets.make_reverb_dataset(
      7     server_address=replay_server_address,
      8     batch_size=256)

File /mnt/task_runtime/acme/lib/python3.9/site-packages/acme/datasets/reverb.py:116, in make_reverb_dataset(***failed resolving arguments***)
    111 # Create a datasets and interleaves it to create `num_parallel_calls`
    112 # `TrajectoryDataset`s. The initial dataset is infinitely large in order
    113 # to allow `num_parallel_calls` to be set to `tf.data.AUTOTUNE` - this ensures
    114 # that the interleaved dataset is large enough.
    115 dataset = tf.data.Dataset.from_tensors(0).repeat()
--> 116 dataset = dataset.interleave(
    117     map_func=_make_dataset,
    118     cycle_length=num_parallel_calls,
    119     num_parallel_calls=num_parallel_calls,
    120     deterministic=False)
    122 if prefetch_size:
    123   dataset = dataset.prefetch(prefetch_size)

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py:2183, in DatasetV2.interleave(self, map_func, cycle_length, block_length, num_parallel_calls, deterministic, name)
   2180   return InterleaveDataset(
   2181       self, map_func, cycle_length, block_length, name=name)
   2182 else:
-> 2183   return ParallelInterleaveDataset(
   2184       self,
   2185       map_func,
   2186       cycle_length,
   2187       block_length,
   2188       num_parallel_calls,
   2189       deterministic=deterministic,
   2190       name=name)

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py:5368, in ParallelInterleaveDataset.__init__(self, input_dataset, map_func, cycle_length, block_length, num_parallel_calls, buffer_output_elements, prefetch_input_elements, deterministic, name)
   5366 """See `Dataset.interleave()` for details."""
   5367 self._input_dataset = input_dataset
-> 5368 self._map_func = structured_function.StructuredFunctionWrapper(
   5369     map_func, self._transformation_name(), dataset=input_dataset)
   5370 if not isinstance(self._map_func.output_structure, DatasetSpec):
   5371   raise TypeError(
   5372       "The `map_func` argument must return a `Dataset` object. Got "
   5373       f"{_get_type(self._map_func.output_structure)!r}.")

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/data/ops/structured_function.py:271, in StructuredFunctionWrapper.__init__(self, func, transformation_name, dataset, input_classes, input_shapes, input_types, input_structure, add_to_graph, use_legacy_function, defun_kwargs)
    264       warnings.warn(
    265           "Even though the `tf.config.experimental_run_functions_eagerly` "
    266           "option is set, this option does not apply to tf.data functions. "
    267           "To force eager execution of tf.data functions, please use "
    268           "`tf.data.experimental.enable_debug_mode()`.")
    269     fn_factory = trace_tf_function(defun_kwargs)
--> 271 self._function = fn_factory()
    272 # There is no graph to add in eager mode.
    273 add_to_graph &= not context.executing_eagerly()

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/eager/function.py:3070, in Function.get_concrete_function(self, *args, **kwargs)
   3061 def get_concrete_function(self, *args, **kwargs):
   3062   """Returns a `ConcreteFunction` specialized to inputs and execution context.
   3063 
   3064   Args:
   (...)
   3068        or `tf.Tensor` or `tf.TensorSpec`.
   3069   """
-> 3070   graph_function = self._get_concrete_function_garbage_collected(
   3071       *args, **kwargs)
   3072   graph_function._garbage_collector.release()  # pylint: disable=protected-access
   3073   return graph_function

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/eager/function.py:3036, in Function._get_concrete_function_garbage_collected(self, *args, **kwargs)
   3034   args, kwargs = None, None
   3035 with self._lock:
-> 3036   graph_function, _ = self._maybe_define_function(args, kwargs)
   3037   seen_names = set()
   3038   captured = object_identity.ObjectIdentitySet(
   3039       graph_function.graph.internal_captures)

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/eager/function.py:3292, in Function._maybe_define_function(self, args, kwargs)
   3288   return self._define_function_with_shape_relaxation(
   3289       args, kwargs, flat_args, filtered_flat_args)
   3291 self._function_cache.add_call_context(cache_key.call_context)
-> 3292 graph_function = self._create_graph_function(args, kwargs)
   3293 self._function_cache.add(cache_key, cache_key_deletion_observer,
   3294                          graph_function)
   3296 return graph_function, filtered_flat_args

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/eager/function.py:3130, in Function._create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3125 missing_arg_names = [
   3126     "%s_%d" % (arg, i) for i, arg in enumerate(missing_arg_names)
   3127 ]
   3128 arg_names = base_arg_names + missing_arg_names
   3129 graph_function = ConcreteFunction(
-> 3130     func_graph_module.func_graph_from_py_func(
   3131         self._name,
   3132         self._python_function,
   3133         args,
   3134         kwargs,
   3135         self.input_signature,
   3136         autograph=self._autograph,
   3137         autograph_options=self._autograph_options,
   3138         arg_names=arg_names,
   3139         override_flat_arg_shapes=override_flat_arg_shapes,
   3140         capture_by_value=self._capture_by_value),
   3141     self._function_attributes,
   3142     function_spec=self.function_spec,
   3143     # Tell the ConcreteFunction to clean up its graph once it goes out of
   3144     # scope. This is not the default behavior since it gets used in some
   3145     # places (like Keras) where the FuncGraph lives longer than the
   3146     # ConcreteFunction.
   3147     shared_func_graph=False)
   3148 return graph_function

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py:1161, in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes, acd_record_initial_resource_uses)
   1158 else:
   1159   _, original_func = tf_decorator.unwrap(python_func)
-> 1161 func_outputs = python_func(*func_args, **func_kwargs)
   1163 # invariant: `func_outputs` contains only Tensors, CompositeTensors,
   1164 # TensorArrays and `None`s.
   1165 func_outputs = nest.map_structure(convert, func_outputs,
   1166                                   expand_composites=True)

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/data/ops/structured_function.py:248, in StructuredFunctionWrapper.__init__.<locals>.trace_tf_function.<locals>.wrapped_fn(*args)
    242 @eager_function.defun_with_attributes(
    243     input_signature=structure.get_flat_tensor_specs(
    244         self._input_structure),
    245     autograph=False,
    246     attributes=defun_kwargs)
    247 def wrapped_fn(*args):  # pylint: disable=missing-docstring
--> 248   ret = wrapper_helper(*args)
    249   ret = structure.to_tensor_list(self._output_structure, ret)
    250   return [ops.convert_to_tensor(t) for t in ret]

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/data/ops/structured_function.py:177, in StructuredFunctionWrapper.__init__.<locals>.wrapper_helper(*args)
    175 if not _should_unpack(nested_args):
    176   nested_args = (nested_args,)
--> 177 ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
    178 if _should_pack(ret):
    179   ret = tuple(ret)

File /mnt/task_runtime/acme/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py:692, in convert.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    690 except Exception as e:  # pylint:disable=broad-except
    691   if hasattr(e, 'ag_error_metadata'):
--> 692     raise e.ag_error_metadata.to_exception(e)
    693   else:
    694     raise

ValueError: in user code:

    File "/mnt/task_runtime/acme/lib/python3.9/site-packages/acme/datasets/reverb.py", line 96, in _make_dataset  *
        dataset = reverb.TrajectoryDataset.from_table_signature(
    File "/mnt/task_runtime/acme/lib/python3.9/site-packages/reverb/trajectory_dataset.py", line 190, in from_table_signature  *
        raise ValueError(

    ValueError: Table priority_table at localhost:23040 does not have a signature.
```

Any clear way to address this? These are being run via a Jupyter notebook on a remote server.

**Comment by sabelaraga** [comment]
Hey, how is the priority_table defined?

**Comment by rdevon** [comment]
I believe I've solved it here:
https://github.com/deepmind/acme/issues/215
